spring:
  data:
    mongodb:
      username: setyuth
      password: setyuth
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
